# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vacancy_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import vacancy_pb2 as vacancy__pb2
from . import rpc_create_vacancy_pb2 as rpc__create__vacancy__pb2
from . import rpc_update_vacancy_pb2 as rpc__update__vacancy__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15vacancy_service.proto\x12\x02pb\x1a\rvacancy.proto\x1a\x18rpc_create_vacancy.proto\x1a\x18rpc_update_vacancy.proto\"O\n\x13GetVacanciesRequest\x12\x11\n\x04page\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x12\n\x05limit\x18\x02 \x01(\x03H\x01\x88\x01\x01\x42\x07\n\x05_pageB\x08\n\x06_limit\"\x1c\n\x0eVacancyRequest\x12\n\n\x02Id\x18\x01 \x01(\t\"(\n\x15\x44\x65leteVacancyResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xc9\x02\n\x0eVacancyService\x12@\n\rCreateVacancy\x12\x18.pb.CreateVacancyRequest\x1a\x13.pb.VacancyResponse\"\x00\x12\x37\n\nGetVacancy\x12\x12.pb.VacancyRequest\x1a\x13.pb.VacancyResponse\"\x00\x12\x38\n\x0cGetVacancies\x12\x17.pb.GetVacanciesRequest\x1a\x0b.pb.Vacancy\"\x00\x30\x01\x12@\n\rUpdateVacancy\x12\x18.pb.UpdateVacancyRequest\x1a\x13.pb.VacancyResponse\"\x00\x12@\n\rDeleteVacancy\x12\x12.pb.VacancyRequest\x1a\x19.pb.DeleteVacancyResponse\"\x00\x42\x14Z\x12\x63yrex/vacancies/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vacancy_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022cyrex/vacancies/pb'
  _globals['_GETVACANCIESREQUEST']._serialized_start=96
  _globals['_GETVACANCIESREQUEST']._serialized_end=175
  _globals['_VACANCYREQUEST']._serialized_start=177
  _globals['_VACANCYREQUEST']._serialized_end=205
  _globals['_DELETEVACANCYRESPONSE']._serialized_start=207
  _globals['_DELETEVACANCYRESPONSE']._serialized_end=247
  _globals['_VACANCYSERVICE']._serialized_start=250
  _globals['_VACANCYSERVICE']._serialized_end=579
# @@protoc_insertion_point(module_scope)
